import { useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { CategoryChip } from "@/components/category-chip";
import { Toast } from "@/components/toast";
import { ScreenContainer } from "@/components/screen-container";
import { categories, type Category } from "@/src/data/providers";
import { colors, fonts, radius, spacing } from "@/src/design/tokens";
import { haptic } from "@/src/lib/haptics";
export function RecommendScreen() { const [service, setService] = useState(""); const [note, setNote] = useState(""); const [category, setCategory] = useState<Exclude<Category, "Todas">>("Casa"); const [feedback, setFeedback] = useState<{ tone: "success" | "error"; message: string } | null>(null); const publish = () => { if (!service.trim()) { haptic.error(); setFeedback({ tone: "error", message: "Conte o nome do serviço ou profissional para continuar." }); return; } haptic.success(); setFeedback({ tone: "success", message: `Indicação de ${service.trim()} salva como rascunho.` }); setService(""); setNote(""); }; return <ScreenContainer edges={["top", "left", "right"]} style={styles.safeArea}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>COMPARTILHE O QUE FUNCIONA</Text><Text style={styles.title}>Uma boa indicação começa com uma história.</Text><Text style={styles.subtitle}>Ajude seus vizinhos a escolherem com mais confiança. Leva menos de dois minutos.</Text><View style={styles.form}><Step number="1" title="O que você quer indicar?"><Text style={styles.label}>Nome do serviço ou profissional</Text><TextInput value={service} onChangeText={setService} placeholder="Ex.: Studio da Ana" placeholderTextColor={colors.muted} returnKeyType="next" accessibilityLabel="Nome do serviço ou profissional" style={styles.input} /></Step><Step number="2" title="Em qual categoria?"><View style={styles.categoryWrap}>{categories.filter((item) => item !== "Todas").map((item) => <CategoryChip key={item} label={item} selected={category === item} onPress={() => setCategory(item as Exclude<Category, "Todas">)} />)}</View></Step><Step number="3" title="Por que você recomenda?"><Text style={styles.label}>Sua experiência (opcional)</Text><TextInput value={note} onChangeText={setNote} multiline placeholder="Conte o que fez essa experiência valer a indicação..." placeholderTextColor={colors.muted} accessibilityLabel="Sua experiência" style={[styles.input, styles.textarea]} /></Step><View style={styles.notice}><MaterialIcons name="verified-user" size={19} color={colors.primary} /><Text style={styles.noticeText}><Text style={styles.noticeStrong}>Sua indicação ficará visível para a vizinhança.</Text>{"\n"}Você poderá editar ou remover depois.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Publicar indicação" onPress={publish} style={({ pressed }) => [styles.publish, pressed && styles.pressed]}><MaterialIcons name="send" size={18} color={colors.surface} /><Text style={styles.publishText}>Publicar indicação</Text></Pressable><Toast feedback={feedback} /></View></ScrollView></KeyboardAvoidingView></ScreenContainer>; }
function Step({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <View style={styles.step}><View style={styles.stepHead}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{number}</Text></View><Text style={styles.stepTitle}>{title}</Text></View><View style={styles.stepBody}>{children}</View></View>; }
const styles = StyleSheet.create({ flex: { flex: 1 }, safeArea: { backgroundColor: colors.bgApp }, content: { padding: spacing.lg, paddingBottom: 40 }, eyebrow: { color: colors.primaryDeep, fontFamily: fonts.extraBold, fontSize: 10, letterSpacing: 1.2, marginTop: spacing.xs }, title: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 29, lineHeight: 36, letterSpacing: -0.8, marginTop: spacing.sm }, subtitle: { color: colors.muted, fontFamily: fonts.medium, fontSize: 14, lineHeight: 21, marginTop: spacing.sm }, form: { marginTop: spacing.xl, padding: spacing.lg, borderRadius: radius.card, backgroundColor: colors.surface, shadowColor: colors.shadow, shadowOpacity: 0.1, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 3 }, step: { marginBottom: spacing.xl }, stepHead: { flexDirection: "row", alignItems: "center", gap: spacing.sm }, stepNumber: { width: 25, height: 25, borderRadius: 13, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, stepNumberText: { color: colors.surface, fontFamily: fonts.bold, fontSize: 12 }, stepTitle: { color: colors.text, fontFamily: fonts.bold, fontSize: 15 }, stepBody: { marginLeft: 34, marginTop: spacing.md }, label: { color: colors.muted, fontFamily: fonts.semibold, fontSize: 12, marginBottom: 6 }, input: { minHeight: 50, paddingHorizontal: spacing.md, borderRadius: radius.control, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSoft, color: colors.text, fontFamily: fonts.medium, fontSize: 14 }, textarea: { minHeight: 112, paddingTop: spacing.md, textAlignVertical: "top" }, categoryWrap: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, notice: { flexDirection: "row", alignItems: "flex-start", gap: spacing.sm, padding: spacing.md, marginTop: -4, marginBottom: spacing.md, borderRadius: radius.control, backgroundColor: colors.surfaceSoft }, noticeText: { flex: 1, color: colors.muted, fontFamily: fonts.medium, fontSize: 12, lineHeight: 18 }, noticeStrong: { color: colors.text, fontFamily: fonts.bold }, publish: { minHeight: 52, borderRadius: radius.control, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: spacing.xs, backgroundColor: colors.primary }, publishText: { color: colors.surface, fontFamily: fonts.bold, fontSize: 14 }, pressed: { opacity: 0.84, transform: [{ scale: 0.98 }] } });
