import { useMemo, useState } from "react";
import { FlatList, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { CategoryChip } from "@/components/category-chip";
import { ProviderCard } from "@/components/provider-card";
import { ScreenContainer } from "@/components/screen-container";
import { categories, filterProviders, type Category } from "@/src/data/providers";
import { colors, fonts, radius, spacing } from "@/src/design/tokens";
export function ExploreScreen() { const [search, setSearch] = useState(""); const [category, setCategory] = useState<Category>("Todas"); const filtered = useMemo(() => filterProviders(search, category), [category, search]); return <ScreenContainer edges={["top", "left", "right"]} style={styles.safeArea}><FlatList data={filtered} keyExtractor={(item) => item.id} renderItem={({ item }) => <ProviderCard provider={item} />} contentContainerStyle={styles.list} keyboardShouldPersistTaps="handled" ListHeaderComponent={<View><Text style={styles.eyebrow}>EXPLORAR</Text><Text style={styles.title}>O que sua vizinhança recomenda.</Text><View style={styles.search}><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Buscar serviço, nome ou categoria" placeholderTextColor={colors.muted} returnKeyType="done" accessibilityLabel="Buscar serviço, nome ou categoria" style={styles.input} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map((item) => <CategoryChip key={item} label={item} selected={category === item} onPress={() => setCategory(item)} />)}</ScrollView><View style={styles.resultRow}><Text style={styles.resultText}>{filtered.length} {filtered.length === 1 ? "recomendação encontrada" : "recomendações encontradas"}</Text>{(search || category !== "Todas") ? <Text onPress={() => { setSearch(""); setCategory("Todas"); }} accessibilityRole="button" style={styles.clear}>Limpar</Text> : null}</View></View>} ListEmptyComponent={<View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="search-off" size={28} color={colors.primary} /></View><Text style={styles.emptyTitle}>Nenhum achado por aqui.</Text><Text style={styles.emptyText}>Tente outro serviço ou limpe os filtros para ver as indicações da vizinhança.</Text></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ safeArea: { backgroundColor: colors.bgApp }, list: { paddingBottom: 28 }, eyebrow: { color: colors.primaryDeep, fontFamily: fonts.extraBold, fontSize: 10, letterSpacing: 1.2, paddingHorizontal: spacing.lg, marginTop: spacing.lg }, title: { color: colors.text, fontFamily: fonts.extraBold, fontSize: 27, lineHeight: 34, letterSpacing: -0.8, paddingHorizontal: spacing.lg, marginTop: spacing.xs }, search: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: spacing.sm, marginHorizontal: spacing.lg, marginTop: spacing.lg, paddingHorizontal: spacing.md, borderRadius: radius.control, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, input: { flex: 1, minHeight: 48, color: colors.text, fontFamily: fonts.medium, fontSize: 14 }, chips: { gap: spacing.xs, paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.xs }, resultRow: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: spacing.lg, marginVertical: spacing.md }, resultText: { color: colors.muted, fontFamily: fonts.semibold, fontSize: 12 }, clear: { color: colors.primary, fontFamily: fonts.bold, fontSize: 12 }, empty: { alignItems: "center", paddingHorizontal: 44, paddingTop: 54 }, emptyIcon: { alignItems: "center", justifyContent: "center", width: 64, height: 64, borderRadius: 22, backgroundColor: colors.surfaceSoft }, emptyTitle: { color: colors.text, fontFamily: fonts.bold, fontSize: 19, marginTop: spacing.lg }, emptyText: { color: colors.muted, fontFamily: fonts.medium, fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: spacing.xs } });
